SET IDENTITY_INSERT [dbo].[ActorTable] ON
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (1, N'Keanu Reeves', N'1964', NULL, N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (2, N'Laurence Fishburne', N'1961', NULL, N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (3, N'Joe Pantoliano', N'1951', NULL, N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (4, N'Julian Arahanga', N'1972', NULL, N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (5, N'Marcus Chong', N'1967', NULL, N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (6, N'Paul Goddard', N'1963', NULL, N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (7, N'Anthony Ray Parker', N'1958', NULL, N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (8, N'Carrie-Anne Moss', N'1967', NULL, N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (9, N'Hugo Weaving', N'1960', NULL, N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (10, N'Gloria Foster', N'1933', N'2001', N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (11, N'Belinda McClory', N'1968', NULL, N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (12, N'Robert Taylor', N'1963', NULL, N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (13, N'Ada Nicodemou', N'1977', NULL, N'The Matrix')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (14, N'Leonardo DiCaprio', N'1974', NULL, N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (15, N'Kate Winslet', N'1975', NULL, N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (16, N'Billy Zane', N'1966', NULL, N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (17, N'Kathy Bates', N'1948', NULL, N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (18, N'Frances Fisher', N'1952', NULL, N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (19, N'Gloria Stuart', N'1910', N'2010', N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (20, N'Bill Paxton', N'1955', N'2017', N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (21, N'Bernard Hill', N'1944', NULL, N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (22, N'David Warner', N'1941', N'2022', N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (23, N'Victor Garber', N'1949', NULL, N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (24, N'Jonathan Hyde', N'1948', NULL, N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (25, N'Suzy Amis', N'1962', NULL, N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (26, N'Danny Nucci', N'1968', NULL, N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (27, N'Jason Barry', N'1972', NULL, N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (28, N'Ewan Stewart', N'1957', NULL, N'Titanic')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (29, N'Tom Cruise', N'1962', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (30, N'Tim Robbins', N'1958', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (31, N'Kelly McGillis', N'1957', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (32, N'Val Kilmer', N'1959', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (33, N'Anthony Edwards', N'1962', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (34, N'Tom Skerritt', N'1933', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (35, N'Michael Ironside', N'1950', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (36, N'John Stockwell', N'1961', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (37, N'Barry Tubb', N'1963', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (38, N'Rick Rossovich', N'1957', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (39, N'Clarence Gilyard Jr.', N'1955', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (40, N'Whip Hubley', N'1957', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (41, N'James Tolkan', N'1931', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (42, N'Meg Ryan', N'1961', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (43, N'Adrian Pasdar', N'1965', NULL, N'Top Gun')
INSERT INTO [dbo].[ActorTable] ([ActorId], [Name], [BirthYear], [DeathYear], [PlayedIn]) VALUES (44, N'Duke Stroud', N'1938', NULL, N'Top Gun')
SET IDENTITY_INSERT [dbo].[ActorTable] OFF
