SET IDENTITY_INSERT [dbo].[Actor] ON
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (1, N'Keanu Reeves', N'1964', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (2, N'Laurence Fishburne', N'1961', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (3, N'Joe Pantoliano', N'1951', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (4, N'Julian Arahanga', N'1972', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (5, N'Marcus Chong', N'1967', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (6, N'Paul Goddard', N'1963', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (7, N'Anthony Ray Parker', N'1958', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (8, N'Carrie-Anne Moss', N'1967', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (9, N'Hugo Weaving', N'1960', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (10, N'Gloria Foster', N'1933', N'2001')
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (11, N'Belinda McClory', N'1968', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (12, N'Robert Taylor', N'1963', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (13, N'Ada Nicodemou', N'1977', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (14, N'Leonardo DiCaprio', N'1974', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (15, N'Kate Winslet', N'1975', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (16, N'Billy Zane', N'1966', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (17, N'Kathy Bates', N'1948', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (18, N'Frances Fisher', N'1952', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (19, N'Gloria Stuart', N'1910', N'2010')
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (20, N'Bill Paxton', N'1955', N'2017')
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (21, N'Bernard Hill', N'1944', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (22, N'David Warner', N'1941', N'2022')
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (23, N'Victor Garber', N'1949', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (24, N'Jonathan Hyde', N'1948', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (25, N'Suzy Amis', N'1962', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (26, N'Danny Nucci', N'1968', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (27, N'Jason Barry', N'1972', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (28, N'Ewan Stewart', N'1957', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (29, N'Tom Cruise', N'1962', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (30, N'Tim Robbins', N'1958', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (31, N'Kelly McGillis', N'1957', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (32, N'Val Kilmer', N'1959', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (33, N'Anthony Edwards', N'1962', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (34, N'Tom Skerritt', N'1933', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (35, N'Michael Ironside', N'1950', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (36, N'John Stockwell', N'1961', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (37, N'Barry Tubb', N'1963', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (38, N'Rick Rossovich', N'1957', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (39, N'Clarence Gilyard Jr.', N'1955', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (40, N'Whip Hubley', N'1957', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (41, N'James Tolkan', N'1931', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (42, N'Meg Ryan', N'1961', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (43, N'Adrian Pasdar', N'1965', NULL)
INSERT INTO [dbo].[Actor] ([ActorId], [Name], [BirthYear], [DeathYear]) VALUES (44, N'Duke Stroud', N'1938', NULL)
SET IDENTITY_INSERT [dbo].[Actor] OFF
